---
title: "Shinydashboard"
author: "Bramack"
date: "2024-06-28"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(shiny)
library(shinydashboard)
library(DT)
```


```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Project Outcomes Dashboard"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
    )),
  dashboardBody(
    tabItems(
      tabItem(tabName = "dashboard",
              fluidRow(
                box(title = "Progress Overview", width = 12, solidHeader = TRUE, status = "primary",
                    DTOutput("progressTable"))),
              fluidRow(
                box(title = "Progress Plot", width = 12, solidHeader = TRUE, status = "primary",
                    plotOutput("progressPlot")))))))
server <- function(input, output) {
```


```{r}
# Data
  project_data <- data.frame(
    ProjectOutcome = c("Annual HIV cohort reports generated for 47 counties.",
                       "National DQA reports for 47 counties.",
                       "County-specific DQA/DQI reports for HIV programs.",
                       "Enhanced skills and capabilities in surveillance units."),
    Q1 = c(10, 20, 50, 25),
    Q2 = c(20, 10, 20, 50),
    Q3 = c(50, 50, 10, 75),
    Q4 = c(100, 100, 100, 100)
  )
```


```{r}
# Render data table
  output$progressTable <- renderDT({
    datatable(project_data, options = list(pageLength = 5))
  })
  
  # Render plot
  output$progressPlot <- renderPlot({
    barplot(as.matrix(project_data[ , -1]), beside = TRUE, col = rainbow(4),
            legend = project_data$ProjectOutcome, args.legend = list(x = "topright"))
    title(main = "Project Progress by Quarter", xlab = "Quarter", ylab = "Percentage")
  })
 }
```


```{r}
shinyApp(ui, server)
```

